### ISSUE TITLE
Overlay network lost packet occasionally even connect to container in same host 

### ISSUE THREAD

**Issue by mimousewu** [docker/swarm-library-image#11]
I was deploying docker daemon v1.11.2 and swarm 1.2.4-rc2 to our production environment. I have only 2 nodes, 1 of them is the swarm master itself. but in some reasons, sometimes, the network lost packets while try to ping from one container to other. It mostly happened in days later.
Now, I have to expose all ports outside and use host ip address and exposed ports to combine our services. Thank god, it works fine. But I still want to get this fixed.
![6 pic_hd](https://cloud.githubusercontent.com/assets/7788283/17729402/991de3aa-6496-11e6-97cd-b56fbefc845c.jpg)

**Comment by dongluochen** [comment]
@mimousewu This repository is for swarm release. I'll close this issue here. 

If you think this is a overlay network issue with docker engine, please open an issue at https://github.com/docker/libnetwork. 

If you think this is a swarm issue, please open an issue at https://github.com/docker/swarm.

**Comment by mimousewu** [comment]
Thanks
