### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker/swarm-library-image#15]
I wonder if you are supportive this image for arm64 architecture

**Comment by tianon** [comment]
An approach like what I've done in https://github.com/docker/distribution-library-image/pull/74 could work here too (and I'd be happy to do the implementation work), if this is something the maintainers are hip to. :pray: :heart:

**Comment by lag-linaro** [comment]
ARM64 servers are going to be very big in the Enterprise space.

It's important that this work is carried out sooner rather than later.

And it's great to have volunteers who are willing to actually do the enablement.

@tianon would it be worth making the changes and simply submit a PR, as you did with  docker/distribution?

**Comment by lag-linaro** [comment]
@tianon, not much activity in the Issues or Pull Request sections.

Is this project actively maintained?

**Comment by lag-linaro** [comment]
@nishanttotla I see that you recently bumped the binary version.

How are you creating these binaries?  Any chance you can create one for ARM64?

**Comment by lag-linaro** [comment]
@nishanttotla any news on this?

**Comment by suihkulokki** [comment]
Is this still maintained, or is the new swarm mode now what everyone uses?

**Comment by bhcopeland** [comment]
Is there any update on this?

**Comment by justincormack** [comment]
Classic Swarm is now archived see docker/classicswarm#2986
